FROM clojure:lein
LABEL maintainer sturm@uni-trier.de
# RUN apt-get update && apt-get install -y
# ENV TZ=Europe/Berlin
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# WORKDIR dashboard
CMD [ "lein", "repl"  ]
